---
- hosts:
  - c7-1

  become: yes
  vars_files:
    - roles/common/group_vars/all.yml

  tasks:
    - import_tasks: roles/common/tasks/setup-network.yml
    - import_tasks: roles/common/tasks/setup-sysctl.yml
    - import_tasks: roles/common/tasks/setup-limits.yml
    - import_tasks: roles/common/tasks/install-rpms-00.yml
    - import_tasks: roles/common/tasks/install-rpms-01.yml
    - import_tasks: roles/common/tasks/add-group.yml
    - import_tasks: roles/common/tasks/add-oracle.yml
    - import_tasks: roles/common/tasks/setup-selinux.yml
    - import_tasks: roles/common/tasks/setup-hosts.yml
