---

  - name: add oracle group
    group:
      gid  : "{{ item.gid }}"
      name : "{{ item.name }}"
      state: present
    with_items:
      - { name: oinstall,  gid: 54321 }
      - { name: dba,       gid: 54322 }
      - { name: oper,      gid: 54323 }
      - { name: backupdba, gid: 54324 }
      - { name: dgdba,     gid: 54325 }
      - { name: kmdba,     gid: 54326 }
      - { name: asmdba,    gid: 54327 }
      - { name: asmoper,   gid: 54328 }
      - { name: asmadmin,  gid: 54329 }
      - { name: racdba,    gid: 54330 }
